import React,{useEffect,useMemo,useRef,useState}from'react';
import{createClient}from'@supabase/supabase-js';
import{MAP_W,MAP_H,BULLET_RADIUS,SPEED,BOT_SPEED,FIRE_COOLDOWN,BOT_FIRE_COOLDOWN,PLAYER_TTL,JOYSTICK_RADIUS,MAX_PLAYERS_PER_ROOM,BOT_COUNT,MAX_LEVEL,ORBS_PER_KILL,ROOMS}from'./game/constants.js';
import{makeBots,respawnBot}from'./game/bots.js';
import{clamp,rand,makeId,isMobileLike,getRadius,getMaxHp,getDamage,getScale,xpNeed,collidesWithBlock}from'./game/math.js';
import{drawGround,drawBlocks,drawTank,drawBullet,drawMiniMap,drawOrb}from'./game/renderV2.js';
import{parsePlayerName}from'./game/bonus.js';
import{distance,nearest,levelSpeed,safePosition,smartMove,moveTankSafe,updateStuck}from'./game/pathing.js';

const URL=import.meta.env.VITE_SUPABASE_URL,KEY=import.meta.env.VITE_SUPABASE_ANON_KEY;
const CENTER={x:MAP_W/2,y:MAP_H/2},DROP_MS=120000,GUARD_LEVEL=10,GUARD_COUNT=4;
const mkClient=()=>URL&&KEY?createClient(URL,KEY,{realtime:{params:{eventsPerSecond:30}}}):null;
const deathDrop=l=>l>=25?16:l>=15?8:l>=5?4:ORBS_PER_KILL;
const levelLoss=l=>l<=1?0:Math.max(1,Math.floor(l*.1));
const need=t=>t?.unlimitedLevel?Math.max(1,t.level||1):xpNeed(t.level||1);
const canLevel=t=>t?.unlimitedLevel||((t.level||1)<MAX_LEVEL);

function makeGuard(id,i){const a=Math.PI*2/GUARD_COUNT*i,p=safePosition(CENTER.x+Math.cos(a)*260,CENTER.y+Math.sin(a)*260,44);return{id:`guard-${id}-${i}`,name:`Guard ${i+1}`,bot:true,guard:true,level:GUARD_LEVEL,x:p.x,y:p.y,angle:a,dir:a,hp:getMaxHp({level:GUARD_LEVEL}),color:'#ef4444',lastFire:performance.now()+rand(0,BOT_FIRE_COOLDOWN),nextTurn:performance.now()+rand(600,1400),stuck:0,lastX:p.x,lastY:p.y}}
const makeGuards=id=>Array.from({length:GUARD_COUNT},(_,i)=>makeGuard(id,i));
function makeSafeBots(room){return makeBots(room).map(b=>{const p=safePosition(b.x,b.y,getRadius(b));return{...b,x:p.x,y:p.y,xp:0,stuck:0,lastX:p.x,lastY:p.y}})}

export default function App(){const sb=useMemo(mkClient,[]),[name,setName]=useState(localStorage.getItem('tank_name')||`Tank${Math.floor(rand(100,999))}`),[room,setRoom]=useState(localStorage.getItem('tank_room')||ROOMS[0]),[joined,setJoined]=useState(false);if(!sb)return <div className="centerCard"><h1>Нужен Supabase</h1><p>Заполни <b>.env</b>: VITE_SUPABASE_URL и VITE_SUPABASE_ANON_KEY.</p></div>;return <div className="app">{!joined?<Lobby name={name} setName={setName} room={room} setRoom={setRoom} onJoin={()=>{const r=ROOMS.includes(room)?room:ROOMS[0];localStorage.setItem('tank_name',name.trim()||'Player');localStorage.setItem('tank_room',r);setRoom(r);setJoined(true)}}/>:<Game supabase={sb} rawName={name.trim()||'Player'} roomCode={room} onLeave={()=>setJoined(false)}/>}</div>}
function Lobby({name,setName,room,setRoom,onJoin}){return <div className="lobby"><div className="panel hero"><div className="badge">V7 / XP CODES / SMARTER BOTS</div><h1>Tanchiki Online</h1><p>Боты обходят стены, собирают XP, дерутся между собой и рейдят центр.</p></div><div className="panel form"><label>Ник</label><input value={name} maxLength={48} onChange={e=>setName(e.target.value)}/><label>Комната</label><div className="roomGrid">{ROOMS.map((c,i)=><button key={c} type="button" className={`roomButton ${room===c?'active':''}`} onClick={()=>setRoom(c)}>Комната {i+1}<span>до {MAX_PLAYERS_PER_ROOM} игроков + {BOT_COUNT} ботов</span></button>)}</div><button onClick={onJoin}>Войти в бой</button><p className="muted">На телефоне лучше играть горизонтально и на весь экран.</p></div></div>}

function Game({supabase,rawName,roomCode,onLeave}){const parsed=useMemo(()=>parsePlayerName(rawName),[rawName]);
const spawn=useMemo(()=>safePosition(rand(400,MAP_W-400),rand(400,MAP_H-400),44),[]);
const canvasRef=useRef(null),joyRef=useRef(null),knobRef=useRef(null),keys=useRef(new Set()),pointer=useRef({x:5000,y:5000,down:false}),camera=useRef({x:0,y:0,w:1,h:1}),joy=useRef({id:null,dx:0,dy:0}),aimTouchId=useRef(null);
const me=useRef({id:makeId(),name:parsed.name,special:parsed.special,trail:parsed.trail,unlimitedLevel:parsed.unlimitedLevel,trailIntervalMs:parsed.trailIntervalMs||2000,level:parsed.special?5:1,xp:0,x:spawn.x,y:spawn.y,angle:0,hp:parsed.special?getMaxHp({level:5})*3:100,hpMul:parsed.special?3:1,speedMul:parsed.special?2:1,kills:0,deaths:0,lastFire:0,lastTrailDrop:performance.now(),color:parsed.special?'#7c2d12':parsed.trail?'#22c55e':`hsl(${Math.floor(rand(0,360))} 80% 58%)`});
const bots=useRef(makeSafeBots(roomCode)),guards=useRef([]),peers=useRef(new Map()),bullets=useRef([]),orbs=useRef([]),channelRef=useRef(null),nextCrateAt=useRef(performance.now()+DROP_MS);
const[status,setStatus]=useState('Подключение...'),[players,setPlayers]=useState(1),[ui,setUi]=useState({hp:me.current.hp,level:me.current.level,xp:0,nextDrop:120}),[mobile,setMobile]=useState(isMobileLike()),[portrait,setPortrait]=useState(innerHeight>innerWidth&&isMobileLike());
const maxHp=t=>getMaxHp(t)*(t.hpMul||1),sync=()=>setUi({hp:Math.round(me.current.hp),level:me.current.level,xp:me.current.xp,nextDrop:Math.max(0,Math.ceil((nextCrateAt.current-performance.now())/1000))});
const enterFs=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();if(innerHeight>innerWidth)await screen.orientation?.lock?.('landscape');setPortrait(innerHeight>innerWidth&&isMobileLike())}catch{setPortrait(innerHeight>innerWidth&&isMobileLike())}},leave=async()=>{try{await screen.orientation?.lock?.('portrait')}catch{}try{if(document.fullscreenElement)await document.exitFullscreen?.()}catch{}try{screen.orientation?.unlock?.()}catch{}onLeave()};

useEffect(()=>{const f=()=>{setMobile(isMobileLike());setPortrait(innerHeight>innerWidth&&isMobileLike())};f();addEventListener('resize',f);addEventListener('orientationchange',f);document.addEventListener('fullscreenchange',f);return()=>{removeEventListener('resize',f);removeEventListener('orientationchange',f);document.removeEventListener('fullscreenchange',f)}},[]);
useEffect(()=>{const ch=supabase.channel(`tanchiki:${roomCode}`,{config:{broadcast:{self:false},presence:{key:me.current.id}}});channelRef.current=ch;ch.on('broadcast',{event:'state'},({payload})=>{if(payload&&payload.id!==me.current.id)peers.current.set(payload.id,{...payload,seenAt:performance.now()})});ch.on('broadcast',{event:'shot'},({payload})=>{if(payload&&payload.owner!==me.current.id)bullets.current.push({...payload,born:performance.now()})});ch.on('broadcast',{event:'hit'},({payload})=>{if(payload?.target===me.current.id)damageMe(payload.damage||25)});ch.on('broadcast',{event:'crate'},({payload})=>{if(!payload?.id)return;if(!orbs.current.some(o=>o.id===payload.id))orbs.current.push(payload);guards.current=makeGuards(payload.id)});ch.subscribe(async s=>{if(s==='SUBSCRIBED'){await ch.track({id:me.current.id,name:me.current.name,online_at:new Date().toISOString()});setStatus('Онлайн');setTimeout(()=>{if(Object.keys(ch.presenceState()).length>MAX_PLAYERS_PER_ROOM){alert(`Комната заполнена: максимум ${MAX_PLAYERS_PER_ROOM} игроков.`);leave()}},900)}});return()=>ch.unsubscribe()},[supabase,roomCode]);
useEffect(()=>{const d=e=>keys.current.add(e.key.toLowerCase()),u=e=>keys.current.delete(e.key.toLowerCase());addEventListener('keydown',d);addEventListener('keyup',u);const t=setInterval(sync,500);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u);clearInterval(t)}},[]);
useEffect(()=>{const base=joyRef.current,knob=knobRef.current;if(!base||!knob)return;const set=(x,y)=>{const r=base.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,rx=x-cx,ry=y-cy,dd=Math.hypot(rx,ry),a=Math.atan2(ry,rx),lim=Math.min(dd,JOYSTICK_RADIUS);joy.current.dx=dd>4?Math.cos(a)*lim/JOYSTICK_RADIUS:0;joy.current.dy=dd>4?Math.sin(a)*lim/JOYSTICK_RADIUS:0;knob.style.transform=`translate3d(${joy.current.dx*JOYSTICK_RADIUS}px,${joy.current.dy*JOYSTICK_RADIUS}px,0)`},reset=()=>{joy.current={id:null,dx:0,dy:0};knob.style.transform='translate3d(0,0,0)'},block=e=>{e.preventDefault();e.stopPropagation()},down=e=>{block(e);joy.current.id=e.pointerId;base.setPointerCapture?.(e.pointerId);set(e.clientX,e.clientY)},move=e=>{if(joy.current.id!==e.pointerId)return;block(e);set(e.clientX,e.clientY)},up=e=>{if(joy.current.id!==e.pointerId)return;block(e);reset()};base.addEventListener('pointerdown',down);base.addEventListener('pointermove',move);base.addEventListener('pointerup',up);base.addEventListener('pointercancel',up);return()=>{base.removeEventListener('pointerdown',down);base.removeEventListener('pointermove',move);base.removeEventListener('pointerup',up);base.removeEventListener('pointercancel',up)}},[]);
useEffect(()=>{const canvas=canvasRef.current,ctx=canvas.getContext('2d',{alpha:false});let last=performance.now(),send=0,raf=0;const resize=()=>{const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2.5),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);camera.current.w=r.width;camera.current.h=r.height},toWorld=(x,y)=>{const r=canvas.getBoundingClientRect();return{x:camera.current.x+x-r.left,y:camera.current.y+y-r.top}},touch=(arr,id)=>{for(const t of arr)if(t.identifier===id)return t;return null},aim=p=>{if(!p)return;const t=toWorld(p.clientX,p.clientY);me.current.angle=Math.atan2(t.y-me.current.y,t.x-me.current.x);pointer.current={...pointer.current,...t}},moveAim=e=>{if(e.changedTouches){const t=touch(e.changedTouches,aimTouchId.current);if(t)aim(t)}else aim(e)},downAim=e=>{if(e.target.closest?.('.joystick,.fireButton,.topbar'))return;if(e.changedTouches){const t=e.changedTouches[0];aimTouchId.current=t.identifier;aim(t)}else aim(e);pointer.current.down=true;fire()},upAim=e=>{if(e.changedTouches&&aimTouchId.current!==null){const t=touch(e.changedTouches,aimTouchId.current);if(!t)return;aimTouchId.current=null}pointer.current.down=false},fire=()=>{const now=performance.now();if(now-me.current.lastFire<FIRE_COOLDOWN||me.current.hp<=0)return;me.current.lastFire=now;const s=getScale(me.current),a=me.current.angle,b={id:makeId(),owner:me.current.id,damage:getDamage(me.current,34),x:me.current.x+Math.cos(a)*32*s,y:me.current.y+Math.sin(a)*32*s,vx:Math.cos(a)*620,vy:Math.sin(a)*620};bullets.current.push({...b,born:now});channelRef.current?.send({type:'broadcast',event:'shot',payload:b})},loop=now=>{resize();const dt=Math.min(.05,(now-last)/1000);last=now;update(dt,now,fire);updateCamera();draw(ctx,canvas);send+=dt;if(send>.06){send=0;channelRef.current?.send({type:'broadcast',event:'state',payload:{...me.current}})}raf=requestAnimationFrame(loop)};canvas.addEventListener('mousemove',moveAim);canvas.addEventListener('mousedown',downAim);canvas.addEventListener('touchstart',downAim,{passive:true});canvas.addEventListener('touchmove',moveAim,{passive:true});addEventListener('mouseup',upAim);addEventListener('touchend',upAim);addEventListener('touchcancel',upAim);raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);canvas.removeEventListener('mousemove',moveAim);canvas.removeEventListener('mousedown',downAim);canvas.removeEventListener('touchstart',downAim);canvas.removeEventListener('touchmove',moveAim);removeEventListener('mouseup',upAim);removeEventListener('touchend',upAim);removeEventListener('touchcancel',upAim)}},[]);

function spawnCrate(){const crate={id:`crate-${roomCode}-${makeId()}`,kind:'drop',x:CENTER.x,y:CENTER.y,value:Math.floor(rand(15,101)),born:performance.now()};orbs.current=orbs.current.filter(o=>o.kind!=='drop');orbs.current.push(crate);guards.current=makeGuards(crate.id);channelRef.current?.send({type:'broadcast',event:'crate',payload:crate})}
function spawnTrail(now){if(!me.current.trail||now-me.current.lastTrailDrop<me.current.trailIntervalMs)return;me.current.lastTrailDrop=now;const a=me.current.angle+Math.PI,p=safePosition(me.current.x+Math.cos(a)*90,me.current.y+Math.sin(a)*90,18);orbs.current.push({id:`trail-${makeId()}`,kind:'orb',x:p.x,y:p.y,value:Math.floor(rand(1,11)),born:now})}
function addXp(t,amt){t.xp=(t.xp||0)+amt;while(canLevel(t)&&t.xp>=need(t)){t.xp-=need(t);t.level++;t.hp=Math.min(maxHp(t),(t.hp||0)+25)}if(!t.unlimitedLevel&&t.level>=MAX_LEVEL)t.xp=0;if(t===me.current)sync()}
function dropXp(x,y,count=ORBS_PER_KILL,value=1){for(let i=0;i<count;i++){const a=rand(0,Math.PI*2),p=safePosition(x+Math.cos(a)*rand(24,78),y+Math.sin(a)*rand(24,78),18);orbs.current.push({id:makeId(),kind:'orb',x:p.x,y:p.y,value,born:performance.now()})}}
function damageMe(amount){me.current.hp=Math.max(0,me.current.hp-amount);sync();if(me.current.hp<=0){dropXp(me.current.x,me.current.y,deathDrop(me.current.level));const l=levelLoss(me.current.level);if(l){me.current.level=Math.max(1,me.current.level-l);me.current.xp=Math.min(me.current.xp,Math.max(0,need(me.current)-1))}const p=safePosition(rand(400,MAP_W-400),rand(400,MAP_H-400),getRadius(me.current));me.current.x=p.x;me.current.y=p.y;me.current.hp=maxHp(me.current);setTimeout(sync,350)}}
function update(dt,now,fire){if(now>=nextCrateAt.current){spawnCrate();nextCrateAt.current=now+DROP_MS}spawnTrail(now);updatePlayer(dt,fire);updateBots(dt,now);updateGuards(dt,now);collectOrbs();for(const[id,p]of peers.current)if(now-p.seenAt>PLAYER_TTL)peers.current.delete(id);setPlayers(peers.current.size+1);bullets.current=bullets.current.map(b=>({...b,x:b.x+b.vx*dt,y:b.y+b.vy*dt})).filter(b=>now-b.born<2200&&b.x>-80&&b.x<MAP_W+80&&b.y>-80&&b.y<MAP_H+80&&!collidesWithBlock(b.x,b.y,BULLET_RADIUS));resolveHits()}
function find(id){if(id===me.current.id)return me.current;return bots.current.find(b=>b.id===id)||guards.current.find(g=>g.id===id)||null}
function resolveHits(){for(const b of bullets.current){const owner=find(b.owner);if(b.owner===me.current.id)hitAll(b,owner);else if((`${b.owner}`.startsWith('bot-')||`${b.owner}`.startsWith('guard-'))&&Math.hypot(b.x-me.current.x,b.y-me.current.y)<getRadius(me.current)+8){b.born=0;damageMe(b.damage||15)}if(`${b.owner}`.startsWith('bot-')){for(const bot of bots.current)if(bot.id!==b.owner&&bot.hp>0&&Math.hypot(b.x-bot.x,b.y-bot.y)<getRadius(bot)+8)hitTank(b,bot,owner);for(const g of guards.current)if(g.hp>0&&Math.hypot(b.x-g.x,b.y-g.y)<getRadius(g)+8)hitTank(b,g,owner)}if(`${b.owner}`.startsWith('guard-'))for(const bot of bots.current)if(bot.hp>0&&Math.hypot(b.x-bot.x,b.y-bot.y)<getRadius(bot)+8)hitTank(b,bot,owner)}guards.current=guards.current.filter(g=>g.hp>0)}
function hitAll(b,owner){for(const p of peers.current.values())if(Math.hypot(b.x-p.x,b.y-p.y)<25){channelRef.current?.send({type:'broadcast',event:'hit',payload:{target:p.id,from:me.current.id,damage:b.damage||getDamage(me.current,34)}});b.born=0}for(const bot of bots.current)if(bot.hp>0&&Math.hypot(b.x-bot.x,b.y-bot.y)<getRadius(bot)+8)hitTank(b,bot,owner);for(const g of guards.current)if(g.hp>0&&Math.hypot(b.x-g.x,b.y-g.y)<getRadius(g)+8)hitTank(b,g,owner)}
function hitTank(b,t,owner){t.hp-=b.damage||getDamage(owner||me.current,34);b.born=0;if(t.hp<=0){dropXp(t.x,t.y,deathDrop(t.level)*(t.guard?2:1));if(owner&&owner!==t)addXp(owner,t.guard?2:1);if(!t.guard)respawnSafe(t);if(owner===me.current)me.current.kills++}}
function respawnSafe(bot){respawnBot(bot);const p=safePosition(bot.x,bot.y,getRadius(bot));bot.x=p.x;bot.y=p.y;bot.stuck=0;bot.lastX=p.x;bot.lastY=p.y}
function collectOrbs(){const takers=[me.current,...bots.current,...guards.current],keep=[];for(const o of orbs.current){const n=nearest(takers,o,t=>t.hp>0&&Math.hypot(t.x-o.x,t.y-o.y)<=getRadius(t)+(o.kind==='drop'?60:24));if(n)addXp(n.item,o.value);else keep.push(o)}orbs.current=keep}
function updatePlayer(dt,fire){let dx=joy.current.dx,dy=joy.current.dy,k=keys.current;if(k.has('w')||k.has('arrowup'))dy-=1;if(k.has('s')||k.has('arrowdown'))dy+=1;if(k.has('a')||k.has('arrowleft'))dx-=1;if(k.has('d')||k.has('arrowright'))dx+=1;const len=Math.hypot(dx,dy);if(len>.01)moveTankSafe(me.current,dx/len*levelSpeed(me.current,SPEED)*clamp(len,0,1)*dt,dy/len*levelSpeed(me.current,SPEED)*clamp(len,0,1)*dt);if(pointer.current.down)fire()}
function chooseBotTarget(bot){if(distance(bot,me.current)<1650)return me.current;const enemy=[...bots.current.filter(b=>b.id!==bot.id&&b.hp>0),...guards.current.filter(g=>g.hp>0)],e=nearest(enemy,bot,t=>distance(bot,t)<1200);if(e)return e.item;const o=nearest(orbs.current,bot,x=>x.kind!=='drop'||guards.current.length<=1||distance(bot,x)<900);if(o&&o.distance<1300)return o.item;if(orbs.current.some(x=>x.kind==='drop')&&distance(bot,CENTER)<2300)return{x:CENTER.x+rand(-140,140),y:CENTER.y+rand(-140,140)};return null}
function updateBots(dt,now){for(const bot of bots.current){const t=chooseBotTarget(bot);if(t){bot.dir=Math.atan2(t.y-bot.y,t.x-bot.x);bot.angle=bot.dir}else if(now>bot.nextTurn){bot.dir=rand(0,Math.PI*2);bot.nextTurn=now+rand(900,2400);bot.angle=bot.dir}const moved=smartMove(bot,Math.cos(bot.dir)*levelSpeed(bot,BOT_SPEED)*dt,Math.sin(bot.dir)*levelSpeed(bot,BOT_SPEED)*dt);updateStuck(bot,now,moved);if(t&&t.hp!==undefined&&distance(bot,t)<1500&&now-bot.lastFire>BOT_FIRE_COOLDOWN)shoot(bot,now)}}
function updateGuards(dt,now){for(const g of guards.current){const t=nearest([me.current,...bots.current],g,x=>x.hp>0&&distance(g,x)<1700)?.item;if(t){g.dir=Math.atan2(t.y-g.y,t.x-g.x);g.angle=g.dir;if(distance(g,t)>360)smartMove(g,Math.cos(g.dir)*levelSpeed(g,BOT_SPEED*.82)*dt,Math.sin(g.dir)*levelSpeed(g,BOT_SPEED*.82)*dt);if(now-g.lastFire>BOT_FIRE_COOLDOWN*.9)shoot(g,now)}else if(distance(g,CENTER)>340){g.dir=Math.atan2(CENTER.y-g.y,CENTER.x-g.x);g.angle=g.dir;smartMove(g,Math.cos(g.dir)*levelSpeed(g,BOT_SPEED*.65)*dt,Math.sin(g.dir)*levelSpeed(g,BOT_SPEED*.65)*dt)}}}
function shoot(e,now){e.lastFire=now;const s=getScale(e),a=e.angle;bullets.current.push({id:makeId(),owner:e.id,damage:getDamage(e,e.guard?22:15),x:e.x+Math.cos(a)*32*s,y:e.y+Math.sin(a)*32*s,vx:Math.cos(a)*520,vy:Math.sin(a)*520,born:now})}
function updateCamera(){const c=camera.current,tx=clamp(me.current.x-c.w/2,0,Math.max(0,MAP_W-c.w)),ty=clamp(me.current.y-c.h/2,0,Math.max(0,MAP_H-c.h));c.x+=(tx-c.x)*.12;c.y+=(ty-c.y)*.12}
function draw(ctx,canvas){const r=canvas.getBoundingClientRect();ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,r.width,r.height);ctx.save();ctx.translate(-Math.round(camera.current.x),-Math.round(camera.current.y));drawGround(ctx,camera.current);drawBlocks(ctx);for(const o of orbs.current)drawOrb(ctx,o);for(const p of peers.current.values())drawTank(ctx,p,false);for(const b of bots.current)drawTank(ctx,b,false);for(const g of guards.current)drawTank(ctx,g,false);drawTank(ctx,me.current,true);for(const b of bullets.current)drawBullet(ctx,b);ctx.restore();drawMiniMap(ctx,r.width,r.height,me.current,peers.current,[...bots.current,...guards.current],orbs.current)}
return <div className="gameShell">{mobile&&portrait&&<div className="portraitBlocker"><div>Переверните телефон</div><small>Или нажмите кнопку ниже — игра откроется на весь экран и попробует повернуть экран.</small><button onClick={enterFs}>На весь экран и повернуть</button></div>}<header className="topbar"><div><b>Tanchiki</b> / room: <code>{roomCode}</code></div><div className="stats"><span>{status}</span><span>Игроков: {players}/{MAX_PLAYERS_PER_ROOM}</span><span>LVL: {ui.level}{me.current.unlimitedLevel?'':`/${MAX_LEVEL}`}</span><span>XP: {ui.xp}/{need(me.current)}</span><span>HP: {ui.hp}/{maxHp(me.current)}</span><span>DROP: center / {ui.nextDrop}s</span><span>GUARDS: {guards.current.length}</span></div><button className="small" onClick={leave}>Выйти</button></header><canvas ref={canvasRef} className="gameCanvas"/><div className="joystick" ref={joyRef}><div className="joystickRing"/><div className="joystickKnob" ref={knobRef}/></div><button className="fireButton" onPointerDown={e=>{e.stopPropagation();pointer.current.down=true}} onPointerUp={e=>{e.stopPropagation();pointer.current.down=false}} onPointerCancel={e=>{e.stopPropagation();pointer.current.down=false}}>FIRE</button></div>}
